<?php

declare(strict_types=1);

namespace Kilden\Tests\Unit;

use InvalidArgumentException;
use Kilden\IdentitySigner;
use PHPUnit\Framework\TestCase;

final class IdentitySignerTest extends TestCase
{
    /**
     * Every frozen vector from the spec, byte for byte. These tokens were
     * generated by the platform's Go implementation — passing here means a
     * token signed by this SDK verifies in production.
     *
     * @dataProvider specVectors
     * @param array<string, mixed> $traits
     */
    public function testMatchesSpecVectors(string $secret, string $kid, string $sub, int $iat, int $exp, array $traits, string $expected): void
    {
        $signer = new IdentitySigner($secret, ['kid' => $kid]);

        self::assertSame($expected, $signer->signAt($sub, $iat, $exp, $traits));
    }

    /**
     * @return iterable<string, array{string, string, string, int, int, array<string, mixed>, string}>
     */
    public function specVectors(): iterable
    {
        $path = getenv('KILDEN_SPEC_DIR') ?: '../kilden-sdk-spec';
        $file = $path . '/vectors/identity.json';
        if (!is_file($file)) {
            self::markTestSkipped('spec vectors not found at ' . $file);
        }
        /** @var array{vectors: list<array<string, mixed>>} $doc */
        $doc = json_decode((string) file_get_contents($file), true);
        foreach ($doc['vectors'] as $vector) {
            yield (string) $vector['name'] => [
                (string) $vector['secret'],
                (string) $vector['kid'],
                (string) $vector['sub'],
                (int) $vector['iat'],
                (int) $vector['exp'],
                isset($vector['traits']) ? (array) $vector['traits'] : [],
                (string) $vector['token'],
            ];
        }
    }

    public function testSignUsesNowAndTtl(): void
    {
        $signer = new IdentitySigner('secret', ['kid' => 'k1']);
        $before = time();
        $token = $signer->sign('user_1', ['ttl' => 60]);
        $after = time();

        $payload = $this->decodePayload($token);
        self::assertSame('user_1', $payload['sub']);
        self::assertGreaterThanOrEqual($before, $payload['iat']);
        self::assertLessThanOrEqual($after, $payload['iat']);
        self::assertSame($payload['iat'] + 60, $payload['exp']);
        self::assertArrayNotHasKey('traits', $payload);
    }

    public function testDefaultTtlIsOneHour(): void
    {
        $signer = new IdentitySigner('secret', ['kid' => 'k1']);
        $payload = $this->decodePayload($signer->sign('user_1'));

        self::assertSame($payload['iat'] + 3600, $payload['exp']);
    }

    public function testEmptyTraitsAreOmitted(): void
    {
        $signer = new IdentitySigner('secret', ['kid' => 'k1']);
        $payload = $this->decodePayload($signer->sign('user_1', ['traits' => []]));

        self::assertArrayNotHasKey('traits', $payload);
    }

    public function testRequiresKid(): void
    {
        $this->expectException(InvalidArgumentException::class);
        new IdentitySigner('secret');
    }

    public function testRejectsEmptySecret(): void
    {
        $this->expectException(InvalidArgumentException::class);
        new IdentitySigner('', ['kid' => 'k1']);
    }

    public function testRejectsEmptySub(): void
    {
        $signer = new IdentitySigner('secret', ['kid' => 'k1']);
        $this->expectException(InvalidArgumentException::class);
        $signer->sign('');
    }

    /**
     * @dataProvider badTtls
     * @param mixed $ttl
     */
    public function testRejectsTtlOutsideRange($ttl): void
    {
        $signer = new IdentitySigner('secret', ['kid' => 'k1']);
        $this->expectException(InvalidArgumentException::class);
        $signer->sign('user_1', ['ttl' => $ttl]);
    }

    /**
     * @return iterable<string, array{mixed}>
     */
    public function badTtls(): iterable
    {
        yield 'zero' => [0];
        yield 'negative' => [-1];
        yield 'over 7 days' => [604801];
        yield 'not an int' => ['3600'];
    }

    /**
     * @return array<string, mixed>
     */
    private function decodePayload(string $token): array
    {
        $parts = explode('.', $token);
        self::assertCount(3, $parts);

        $b64 = strtr($parts[1], '-_', '+/');
        $b64 .= str_repeat('=', (4 - strlen($b64) % 4) % 4);

        return (array) json_decode((string) base64_decode($b64, true), true);
    }
}
